Draft pool cleanup when first connection receives expired auth error
neo4j/neo4j-go-driver pull request #210
Opened 2021-04-14 10:02 UTC by fbiville

2021-04-14 11:13 UTC, 2hdddg requested changes
Since every connection has a timestamp from when it was used you can use that in combination with a timestamp in the pool to know which connections to remove. You shouldn't need to tag every connection that way.

2021-04-14 11:16 UTC, 2hdddg commented on neo4j/internal/pool/pool.go
> +
Both of these are accessing structures written to from other threads, will not work.

2021-04-14 14:26 UTC, fbiville commented
Changed the PR completely now @2hdddg, let me know if that approach is better.
I'll add more test coverage as soon as you think the approach is OK.

2021-04-14 14:49 UTC, 2hdddg approved these changes
That should do it!
Perhaps a test on bolt4 to ensure it. That should be enough since there is no extra logic needed in the pool

2021-05-03 13:29 UTC, 2hdddg approved these changes

2021-05-03 13:52 UTC, merged